fixes

diff --git a/.github/workflows/ci-idris2.yml b/.github/workflows/ci-idris2.yml
--- a/.github/workflows/ci-idris2.yml
+++ b/.github/workflows/ci-idris2.yml
@@ -57,12 +57,15 @@ jobs:
         uses: actions/checkout@v2
       - name: Download and extract Chez Scheme
         run: |
-          env | sort
-          find "$WIX" -name dark.exe || true
-          tag=$(curl -Is https://github.com/cisco/ChezScheme/releases/latest | awk -F/ '/^Location:/ {print $NF}')
+          echo "$PATH"
+          echo "$PWD"
+          find "$(cygpath -u "${WIX}")" -name dark.exe || echo "dark.exe not found"
+          curl -Is https://github.com/cisco/ChezScheme/releases/latest
+          tag=$(curl -Is https://github.com/cisco/ChezScheme/releases/latest | awk -F/ '/^[Ll]ocation:/ {print $NF}')
           ver=${tag#v}
+          echo "tag=$tag ver=$ver"
           curl -LO https://github.com/cisco/ChezScheme/releases/download/$tag/ChezScheme$ver.exe
-          dark=$(cygpath -m "$WIX")/bin/dark.exe
+          dark=$(cygpath -u "${WIX%\\}")/bin/dark.exe
           "$dark" -x extracted ChezScheme$ver.exe
           msiexec /a extracted/AttachedContainer/ChezScheme64.msi TARGETDIR="$PWD" /qn
           "./Chez Scheme $ver/bin/ta6nt/scheme.exe" --version
@@ -116,7 +119,8 @@ jobs:
           path: 'ChezScheme'
       - name: Configure and Build Chez Scheme
         run: |
-          env | sort
+          echo "$PATH"
+          echo "$PWD"
           cd ChezScheme && ./configure --threads && make
       - name: Set Path
         run: |
